export default app => [
  require('./auth'),
  require('./util'),
  require('./requests'),
  require('./storage'),
  require('./auth'),
  require('./config'),
  require('./coupin'),
  require('./payment'),
  require('./reward'),
  require('./analytics'),
  require('./merchant'),
  require('./admin'),
  require('./adminRequest'),
  require('./adminReward'),
].forEach(entry => entry.default(app));
